# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Ron's Blog
subtitle:
description:
author: Ron
language:
timezone:

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://blog.boolron.info
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: jacman
stylus:
  compress: true

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repo: git@git.coding.net:bool_ron/bool_ron.git
  branch: coding-pages


    ##### 菜单
menu:
  主页: /
  归档: /archives
  关于: /about

#### 控件
widgets:
- category
- tag
- links
- rss

#### RSS
rss: /atom.xml

# #### 图片相关
# imglogo:
#   enable: true               ## 是否显示网站 logo
#   src: img/logo.png
# favicon: img/favicon.ico     ## 网站图标
# apple_icon: img/jacman.jpg   ## 苹果设备上的图标，背景不要透明
# author_img: img/author.jpg   ## 网站底部的博主头像
# banner_img: img/banner.jpg   ## 博客顶部的图片

### 主题颜色
theme_color:
    theme: '#2ca6cb'    ##默认主题颜色为蓝色

close_aside: false      ##是否在文章页面自动关闭侧边栏

#### 首页相关
index:
  expand: true              ## 首页文章是否展开。默认为展开式，显示 Read More。
  excerpt_link: Read More

# #### 作者信息
# author:
#   intro_line1:  "Ron"    ## 网站底部的个人介绍
#   intro_line2:  "This is my Blog!"
#   weibo_verifier:  ## 微博秀的验证码
#   tsina:           ## 用于微博秀和微博分享
#   weibo:           ## 用于显示网站底部社交按钮，下同
#   douban:
#   zhihu:
#   email:
#   twitter:
#   github:
#   facebook:
#   linkedin:
#   google_plus:
#   stackoverflow:


#### 目录
toc:
  article: true   ## 是否在文章中显示目录
  aside: true     ## 是否在侧边栏显示目录

#### 友情链接
links:
  码农圈: https://coderq.com,一个面向程序员交流分享的新一代社区


# #### 评论
# duoshuo_shortname:
# disqus_shortname:

# #### 分享按钮
# jiathis:
#   enable: false   ## 默认使用主题内建分享
#   id:
#   tsina:

# #### 网站统计
# baidu_tongji:
#   enable: false
#   sitecode:      ## 百度统计站点特征码

#### 杂项
ShowCustomFont: true
fancybox: true
totop: true

# #### 自定义搜索
# baidu_search:
#   enable: false
#   id:
#   site: http://zhannei.baidu.com/cse/search